export type Silueta = 'Sirena' | 'Princesa' | 'A-Line' | 'Columna' | 'Recto';
export type Tejido = 'Satén' | 'Terciopelo' | 'Gasa' | 'Crepé' | 'Metalizado' | 'Lentejuelas' | 'Tul' | 'Seda' | 'Organza';
export type ColorCategoria = 'Azul' | 'Verde' | 'Negro' | 'Plata' | 'Dorado' | 'Rojo/Granate' | 'Rosa' | 'Morado' | 'Turquesa' | 'Terracota' | 'Estampado' | 'Blanco';

export interface Vestido {
  id: number;
  nombre: string;
  color: string;
  colorCategoria: ColorCategoria;
  silueta: Silueta;
  tejido: Tejido;
  descripcion: string;
  imagenFrente: string;
  imagenEspalda: string;
  imagenesExtra?: string[];
  precio: number;
}

const BASE = '/vestidos de graduación';

export const vestidos: Vestido[] = [
  {
    id: 1,
    nombre: 'Clara Celeste',
    color: 'Azul Royal',
    colorCategoria: 'Azul',
    silueta: 'A-Line',
    tejido: 'Satén',
    descripcion: 'Vestido largo de satén pesado azul royal con corsé estructurado visible, escote strapless recto, cintura muy definida, falda amplia de caída fluida con tajo profundo y cola ligera.',
    imagenFrente: `${BASE}/1. Clara Celeste  Azul Royal Frente.png`,
    imagenEspalda: `${BASE}/1. Clara Celeste  Azul Royal Espalda.png`,
    precio: 450000,
  },
  {
    id: 2,
    nombre: 'Lola',
    color: 'Verde Esmeralda',
    colorCategoria: 'Verde',
    silueta: 'Recto',
    tejido: 'Satén',
    descripcion: 'Vestido de satén verde esmeralda intenso con corsé estructurado, escote corazón, cintura entallada, falda recta con tajo lateral alto y espalda descubierta con amarres cruzados.',
    imagenFrente: `${BASE}/2. Lola Verde Esmeralda.png`,
    imagenEspalda: `${BASE}/2. Lola Verde Esmeralda Espalda.png`,
    precio: 450000,
  },
  {
    id: 3,
    nombre: 'Tomasa',
    color: 'Azul Marino',
    colorCategoria: 'Azul',
    silueta: 'Recto',
    tejido: 'Satén',
    descripcion: 'Vestido azul marino strapless con drapeado asimétrico en el torso, corsé interno invisible, falda recta de satén pesado con tajo profundo y silueta elegante y moderna.',
    imagenFrente: `${BASE}/3. Tomasa Azul Marino.png`,
    imagenEspalda: `${BASE}/3. Tomasa Azul Marino Espalda.png`,
    precio: 450000,
  },
  {
    id: 4,
    nombre: 'Rebecca',
    color: 'Verde Sage',
    colorCategoria: 'Verde',
    silueta: 'Princesa',
    tejido: 'Tul',
    descripcion: 'Vestido estilo princesa color verde sage, corsé transparente con delicadas varillas visibles, escote corazón, falda multicapa de tul suave con mucho volumen y efecto etéreo.',
    imagenFrente: `${BASE}/4. Rebecca Verde Sage.png`,
    imagenEspalda: `${BASE}/4. Rebecca Verde Sage Espalda.png`,
    precio: 450000,
  },
  {
    id: 5,
    nombre: 'Camila',
    color: 'Negro',
    colorCategoria: 'Negro',
    silueta: 'Sirena',
    tejido: 'Satén',
    descripcion: 'Vestido sirena negro de satén pesado, corsé estructurado, cintura extremadamente marcada, espalda completamente descubierta, escote profundo y tajo frontal elegante.',
    imagenFrente: `${BASE}/5. Camila Negro Ajustado.png`,
    imagenEspalda: `${BASE}/5. Camila Negro Ajustado Espalda.png`,
    precio: 450000,
  },
  {
    id: 6,
    nombre: 'Olivia',
    color: 'Azul Navy',
    colorCategoria: 'Azul',
    silueta: 'Recto',
    tejido: 'Satén',
    descripcion: 'Vestido azul navy con escote Bardot caído sobre los hombros, drapeados elegantes en el busto, corsé interno, falda recta satinada con tajo alto y caída sofisticada.',
    imagenFrente: `${BASE}/6. Olivia Azul Navy.png`,
    imagenEspalda: `${BASE}/6. Olivia Azul Navy Espalda.png`,
    precio: 450000,
  },
  {
    id: 7,
    nombre: 'Estrella',
    color: 'Plata',
    colorCategoria: 'Plata',
    silueta: 'Recto',
    tejido: 'Lentejuelas',
    descripcion: 'Vestido plata brillante con corsé transparente de tul, aplicaciones de pedrería fina distribuidas cuidadosamente, escote strapless, falda recta con transparencias sutiles.',
    imagenFrente: `${BASE}/7. Estrella Plata.png`,
    imagenEspalda: `${BASE}/7. Estrella Plata Espalda.png`,
    precio: 450000,
  },
  {
    id: 8,
    nombre: 'Marta',
    color: 'Gold Mist',
    colorCategoria: 'Dorado',
    silueta: 'Sirena',
    tejido: 'Metalizado',
    descripcion: 'Vestido sirena color moka gold, tejido metalizado de lujo, cuello halter, silueta completamente ajustada, brillo sofisticado y caída elegante tipo alfombra roja.',
    imagenFrente: `${BASE}/8. Marta Gold Mist.png`,
    imagenEspalda: `${BASE}/8. Marta Gold Mist Espalda.png`,
    precio: 450000,
  },
  {
    id: 9,
    nombre: 'Majadas Lentejuelas',
    color: 'Champagne',
    colorCategoria: 'Dorado',
    silueta: 'Recto',
    tejido: 'Lentejuelas',
    descripcion: 'Vestido completamente cubierto por lentejuelas geométricas champagne, cuello halter cerrado, espalda descubierta, corte recto con brillo uniforme y silueta estilizada.',
    imagenFrente: `${BASE}/9. Majadas Lentejuelas.png`,
    imagenEspalda: `${BASE}/9. Majadas Lentejuelas Espalda.png`,
    precio: 450000,
  },
  {
    id: 10,
    nombre: 'Majadas Clásico',
    color: 'Negro',
    colorCategoria: 'Negro',
    silueta: 'Columna',
    tejido: 'Crepé',
    descripcion: 'Vestido negro de crepé premium, espalda completamente abierta, escote discreto delantero, corte minimalista, cola ligera y caída perfecta.',
    imagenFrente: `${BASE}/10. Majadas Clásico.png`,
    imagenEspalda: `${BASE}/10. Majadas Clásico Espalda.png`,
    precio: 450000,
  },
  {
    id: 11,
    nombre: 'Isabel',
    color: 'Burdeo',
    colorCategoria: 'Rojo/Granate',
    silueta: 'Columna',
    tejido: 'Terciopelo',
    descripcion: 'Vestido de terciopelo italiano color burdeo profundo, manga larga asimétrica en un brazo, escote asimétrico, drapeados elegantes y tajo lateral alto.',
    imagenFrente: `${BASE}/11. Isabel Velvet.png`,
    imagenEspalda: `${BASE}/11. Isabel Velvet Espalda.png`,
    precio: 450000,
  },
  {
    id: 12,
    nombre: 'Antonieta',
    color: 'Verde Oscuro',
    colorCategoria: 'Verde',
    silueta: 'Sirena',
    tejido: 'Terciopelo',
    descripcion: 'Vestido verde oscuro de terciopelo, escote recto, tirantes finos ajustables, silueta sirena limpia, tela gruesa con caída elegante.',
    imagenFrente: `${BASE}/12. Antonieta Velvet.png`,
    imagenEspalda: `${BASE}/12. Antonieta Velvet Espalda.png`,
    precio: 450000,
  },
  {
    id: 13,
    nombre: 'Caroline',
    color: 'Azul Petróleo',
    colorCategoria: 'Azul',
    silueta: 'Columna',
    tejido: 'Satén',
    descripcion: 'Vestido satinado azul petróleo con cuello drapeado tipo cowl neck, espalda descubierta, falda fluida de satén pesado con brillo natural.',
    imagenFrente: `${BASE}/13. Caroline Fiesta.png`,
    imagenEspalda: `${BASE}/13. Caroline Fiesta Espalda.png`,
    precio: 450000,
  },
  {
    id: 14,
    nombre: 'Faustina',
    color: 'Turquesa',
    colorCategoria: 'Turquesa',
    silueta: 'Columna',
    tejido: 'Satén',
    descripcion: 'Vestido turquesa intenso, cuello halter, espalda completamente descubierta, largo midi-maxi, caída ligera y satén brillante.',
    imagenFrente: `${BASE}/14. Faustina Turquesa.png`,
    imagenEspalda: `${BASE}/14. Faustina Turquesa Espalda.png`,
    precio: 450000,
  },
  {
    id: 15,
    nombre: 'Julianna',
    color: 'Magenta',
    colorCategoria: 'Rosa',
    silueta: 'A-Line',
    tejido: 'Gasa',
    descripcion: 'Vestido magenta confeccionado en gasa, cuello halter, espalda en V, múltiples volantes en la falda con movimiento muy fluido y romántico.',
    imagenFrente: `${BASE}/15. Julianna Magenta.png`,
    imagenEspalda: `${BASE}/15. Julianna Magenta Espalda 1.png`,
    imagenesExtra: [`${BASE}/15. Julianna Magenta Espalda 2.png`],
    precio: 450000,
  },
  {
    id: 16,
    nombre: 'Camille',
    color: 'Granate',
    colorCategoria: 'Rojo/Granate',
    silueta: 'Columna',
    tejido: 'Satén',
    descripcion: 'Vestido granate de satén pesado, escote caído sobre los hombros, espalda baja, silueta ajustada con acabado elegante y minimalista.',
    imagenFrente: `${BASE}/16. Camille Granate..png`,
    imagenEspalda: `${BASE}/16. Camille Granate Espalda.png`,
    precio: 450000,
  },
  {
    id: 17,
    nombre: 'Isabella',
    color: 'Azul Rey',
    colorCategoria: 'Azul',
    silueta: 'Recto',
    tejido: 'Satén',
    descripcion: 'Vestido azul rey intenso, escote asimétrico de un hombro, corsé interno, tajo alto, falda recta de satén pesado con líneas limpias.',
    imagenFrente: `${BASE}/17. Isabella Azul Rey.png`,
    imagenEspalda: `${BASE}/17. Isabella Azul Rey Espalda.png`,
    precio: 450000,
  },
  {
    id: 18,
    nombre: 'Catarina',
    color: 'Floral',
    colorCategoria: 'Estampado',
    silueta: 'Columna',
    tejido: 'Seda',
    descripcion: 'Vestido lencero de seda natural con estampado floral artístico, escote delicado, tirantes finos, silueta relajada con inspiración Rat & Boa.',
    imagenFrente: `${BASE}/18. Catarina Floral.png`,
    imagenEspalda: `${BASE}/18. Catarina Floral Espalda.png`,
    precio: 450000,
  },
  {
    id: 19,
    nombre: 'Marlene',
    color: 'Morado',
    colorCategoria: 'Morado',
    silueta: 'A-Line',
    tejido: 'Gasa',
    descripcion: 'Vestido morado confeccionado en gasa, corte imperio, falda extremadamente fluida con movimiento ligero y estilo romántico.',
    imagenFrente: `${BASE}/19. Marlene Morado.png`,
    imagenEspalda: `${BASE}/19. Marlene Morado Espalda.png`,
    precio: 450000,
  },
  {
    id: 20,
    nombre: 'Renatta',
    color: 'Verde Botella',
    colorCategoria: 'Verde',
    silueta: 'A-Line',
    tejido: 'Satén',
    descripcion: 'Vestido verde botella con escote asimétrico de un hombro, vuelos discretos en la falda, satén ligero y silueta moderna.',
    imagenFrente: `${BASE}/20. Renatta Verde Botella.png`,
    imagenEspalda: `${BASE}/20. Renatta Verde Botella Espalda.png`,
    precio: 450000,
  },
  {
    id: 21,
    nombre: 'Arella',
    color: 'Rose Gold',
    colorCategoria: 'Rosa',
    silueta: 'Sirena',
    tejido: 'Metalizado',
    descripcion: 'Vestido rose gold de tejido metálico texturizado, brillo elegante, silueta sirena y acabado de lujo con inspiración haute couture.',
    imagenFrente: `${BASE}/21. Arella Rose Gold.png`,
    imagenEspalda: `${BASE}/21. Arella Rose Gold Espalda.png`,
    imagenesExtra: [
      `${BASE}/21.1. Arella Rose Gold Drapeado.png`,
      `${BASE}/21.1. Arella Rose Gold Drapeado Espalda.png`,
    ],
    precio: 450000,
  },
  {
    id: 22,
    nombre: 'Madison',
    color: 'Negro',
    colorCategoria: 'Negro',
    silueta: 'Columna',
    tejido: 'Seda',
    descripcion: 'Vestido negro premium de seda fluida, mangas largas transparentes muy finas, corte elegante, escote discreto y falda recta con movimiento natural.',
    imagenFrente: `${BASE}/22. Madison Largo Negro.png`,
    imagenEspalda: `${BASE}/22. Madison Largo Negro Espalda.png`,
    precio: 450000,
  },
  {
    id: 23,
    nombre: 'Aliana',
    color: 'Terracota',
    colorCategoria: 'Terracota',
    silueta: 'A-Line',
    tejido: 'Crepé',
    descripcion: 'Vestido terracota confeccionado en crepé premium, cintura alta marcada, escote cruzado, falda fluida con líneas minimalistas contemporáneas.',
    imagenFrente: `${BASE}/23. Aliana Terracota.png`,
    imagenEspalda: `${BASE}/23. Aliana Terracota Espalda.png`,
    precio: 450000,
  },
  {
    id: 24,
    nombre: 'Amanda Dupont',
    color: 'Azul & Fucsia',
    colorCategoria: 'Azul',
    silueta: 'A-Line',
    tejido: 'Satén',
    descripcion: 'Vestido bicolor azul intenso y fucsia, escote en V profundo, corte cruzado, falda larga con tajo lateral y estilo elegante juvenil.',
    imagenFrente: `${BASE}/20. Renatta Verde Botella.png`, // placeholder - no image found
    imagenEspalda: `${BASE}/20. Renatta Verde Botella.png`,
    precio: 450000,
  },
  {
    id: 25,
    nombre: 'Pandora',
    color: 'Blanco Cristal',
    colorCategoria: 'Blanco',
    silueta: 'Princesa',
    tejido: 'Organza',
    descripcion: 'Vestido blanco cristal de alta costura, corsé estructurado con ballenas visibles, falda amplia de satén y organza con aplicaciones de cristales finos, confección artesanal de lujo.',
    imagenFrente: `${BASE}/4. Rebecca Verde Sage.png`, // placeholder - no image found
    imagenEspalda: `${BASE}/4. Rebecca Verde Sage Espalda.png`,
    precio: 450000,
  },
  {
    id: 26,
    nombre: 'Valentina',
    color: 'Midnight Navy',
    colorCategoria: 'Azul',
    silueta: 'Columna',
    tejido: 'Satén',
    descripcion: 'Satén pesado azul midnight con cuerpo drapeado de inspiración corsetera, escote corazón con tirantes finos, espalda descubierta profunda en V y falda columna de alta costura.',
    imagenFrente: `${BASE}/26. Valentina Midnight Navy.png`,
    imagenEspalda: `${BASE}/26. Valentina Midnight Navy Espalda.png`,
    precio: 450000,
  },
];

// Unique filter values derived from data
export const siluetas: Silueta[] = ['Sirena', 'Princesa', 'A-Line', 'Columna', 'Recto'];
export const tejidos: Tejido[] = ['Satén', 'Terciopelo', 'Gasa', 'Crepé', 'Metalizado', 'Lentejuelas', 'Tul', 'Seda', 'Organza'];
export const colores: ColorCategoria[] = ['Azul', 'Verde', 'Negro', 'Plata', 'Dorado', 'Rojo/Granate', 'Rosa', 'Morado', 'Turquesa', 'Terracota', 'Estampado', 'Blanco'];
